import DestinationCard from "./DestinationCard";
import { ArrowRight } from "lucide-react";
import Link from "next/link";

const destinations = [
  {
    id: "1",
    title: "Kyoto Serenity",
    location: "Kyoto, Japan",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1470&auto=format&fit=crop",
    rating: 4.9,
    price: "$1,200",
  },
  {
    id: "2",
    title: "Amalfi Coastal Drive",
    location: "Campania, Italy",
    image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=1469&auto=format&fit=crop",
    rating: 4.8,
    price: "$1,850",
  },
  {
    id: "3",
    title: "Bali Retreat",
    location: "Bali, Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1338&auto=format&fit=crop",
    rating: 4.7,
    price: "$890",
  },
  {
    id: "4",
    title: "Swiss Alps Adventure",
    location: "Zermatt, Switzerland",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1470&auto=format&fit=crop",
    rating: 4.9,
    price: "$2,100",
  },
  {
    id: "5",
    title: "Santorini Sunsets",
    location: "Cyclades, Greece",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1374&auto=format&fit=crop",
    rating: 4.8,
    price: "$1,600",
  },
  {
    id: "6",
    title: "Banff Wilderness",
    location: "Alberta, Canada",
    image: "https://images.unsplash.com/photo-1518602164578-cd0074062767?q=80&w=1470&auto=format&fit=crop",
    rating: 4.9,
    price: "$1,150",
  },
];

export default function PopularDestinations() {
  return (
    <section className="py-20 lg:py-32 bg-white dark:bg-slate-950">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12 lg:mb-16">
          <div className="max-w-2xl">
            <h2 className="text-3xl lg:text-5xl font-bold tracking-tight text-slate-900 dark:text-white mb-4">
              Explore Popular <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-sky-500">Destinations</span>
            </h2>
            <p className="text-lg text-slate-600 dark:text-slate-400">
              Discover carefully curated travel experiences generated by our AI based on trending global travel patterns.
            </p>
          </div>
          <Link href="/explore" className="inline-flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-semibold hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors">
            View all destinations <ArrowRight size={20} />
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {destinations.map((dest) => (
            <DestinationCard key={dest.id} {...dest} />
          ))}
        </div>
      </div>
    </section>
  );
}
