"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import DestinationCard from "./DestinationCard";
import DestinationCardSkeleton from "./DestinationCardSkeleton";
import { getDestinations } from "@/lib/api";
import type { ApiDestination } from "@/types/api";

export default function PopularDestinations() {
  const [destinations, setDestinations] = useState<ApiDestination[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getDestinations()
      .then((data) => {
        // Show the first 6 destinations on the home page
        setDestinations(data.slice(0, 6));
      })
      .catch((err: unknown) => {
        const message = err instanceof Error ? err.message : "Failed to load destinations.";
        setError(message);
      })
      .finally(() => setIsLoading(false));
  }, []);

  return (
    <section className="py-20 lg:py-32 bg-white dark:bg-slate-950">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12 lg:mb-16">
          <div className="max-w-2xl">
            <h2 className="text-3xl lg:text-5xl font-bold tracking-tight text-slate-900 dark:text-white mb-4">
              Explore Popular <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-sky-500">Destinations</span>
            </h2>
            <p className="text-lg text-slate-600 dark:text-slate-400">
              Discover carefully curated travel experiences generated by our AI based on trending global travel patterns.
            </p>
          </div>
          <Link href="/explore" className="inline-flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-semibold hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors">
            View all destinations <ArrowRight size={20} />
          </Link>
        </div>

        {/* Error state */}
        {error && (
          <div className="text-center py-16 text-slate-500 dark:text-slate-400">
            <p className="text-lg font-medium">Could not load destinations.</p>
            <p className="text-sm mt-1">{error}</p>
          </div>
        )}

        {/* Loading skeletons */}
        {isLoading && !error && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {Array.from({ length: 6 }).map((_, i) => (
              <DestinationCardSkeleton key={i} />
            ))}
          </div>
        )}

        {/* Loaded destinations */}
        {!isLoading && !error && destinations.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {destinations.map((dest) => (
              <Link key={dest._id} href={`/destinations/${dest._id}`}>
                <DestinationCard
                  id={dest._id}
                  title={dest.title}
                  location={`${dest.location}, ${dest.country}`}
                  image={dest.image}
                  rating={dest.rating}
                  price={`$${dest.budget}`}
                />
              </Link>
            ))}
          </div>
        )}

        {/* Empty state */}
        {!isLoading && !error && destinations.length === 0 && (
          <div className="text-center py-16 text-slate-500 dark:text-slate-400">
            <p className="text-lg font-medium">No destinations available yet.</p>
          </div>
        )}
      </div>
    </section>
  );
}
